import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useEffect } from "react";
import { collection, addDoc, getDocs } from "firebase/firestore";
import { database } from "../firebase";
import Button from "@mui/material/Button";
import { useAppDispatch, useAppSelector } from "../redux/hooks";
import { decrement, increment } from "../redux/counterSlice";

export default function Home() {
  const count = useAppSelector((state) => state.counter.value);
  const dispatch = useAppDispatch();

  const handleClick = () => {
    addDoc(collection(database, "test"), {
      testing: "testing",
    }).then((data) => {
      console.log(data);
    });
  };

  useEffect(() => {
    console.log(count);

    getDocs(collection(database, "users")).then((snapshot) => {
      snapshot.forEach((doc) => {
        console.log(doc.data());
      });
    });
  }, []);

  useEffect(() => {
    console.log(count);
  }, [dispatch]);

  return (
    <>
      <Head>
        <title>BabbleR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Hello there</h1>
        <div>
          <Button variant="contained" onClick={handleClick}>
            Klicka här
          </Button>
          <Button
            variant="contained"
            onClick={() => {
              dispatch(increment());
            }}
          >
            Öka med 1
          </Button>
          <Button
            variant="contained"
            onClick={() => {
              dispatch(decrement());
            }}
          >
            Minska med 1
          </Button>
          <h1>{count}</h1>
        </div>
      </main>
    </>
  );
}
